# golangci-lint configuration used for CI
run:
  tests: true
  timeout: 10m
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: github.com/vmware/go-ipfix

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - unused
    - staticcheck
    - gosec
    - goimports
    - vet
