version: "2"
run:
  build-tags:
    - integration
  tests: true
linters:
  default: none
  enable:
    - gosec
    - govet
    - misspell
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        # This should be re-enabled at some point, but for now it generates a
        # lot of errors.
        - G115 # Potential integer overflow when converting between integer types
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vmware/go-ipfix
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
