codecov:
  token: 61ef0651-a3c3-4b71-8ca6-f82630f39579
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1

ignore:
  - "**/testing/mock_*.go"
