// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/srikartati/go-ipfixlib/pkg/entities (interfaces: Record)

// Package testing is a generated GoMock package.
package testing

import (
	bytes "bytes"
	gomock "github.com/golang/mock/gomock"
	entities "github.com/srikartati/go-ipfixlib/pkg/entities"
	reflect "reflect"
)

// MockRecord is a mock of Record interface
type MockRecord struct {
	ctrl     *gomock.Controller
	recorder *MockRecordMockRecorder
}

// MockRecordMockRecorder is the mock recorder for MockRecord
type MockRecordMockRecorder struct {
	mock *MockRecord
}

// NewMockRecord creates a new mock instance
func NewMockRecord(ctrl *gomock.Controller) *MockRecord {
	mock := &MockRecord{ctrl: ctrl}
	mock.recorder = &MockRecordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRecord) EXPECT() *MockRecordMockRecorder {
	return m.recorder
}

// AddInfoElement mocks base method
func (m *MockRecord) AddInfoElement(arg0 *entities.InfoElement, arg1 interface{}) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInfoElement", arg0, arg1)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInfoElement indicates an expected call of AddInfoElement
func (mr *MockRecordMockRecorder) AddInfoElement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInfoElement", reflect.TypeOf((*MockRecord)(nil).AddInfoElement), arg0, arg1)
}

// GetBuffer mocks base method
func (m *MockRecord) GetBuffer() *bytes.Buffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuffer")
	ret0, _ := ret[0].(*bytes.Buffer)
	return ret0
}

// GetBuffer indicates an expected call of GetBuffer
func (mr *MockRecordMockRecorder) GetBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuffer", reflect.TypeOf((*MockRecord)(nil).GetBuffer))
}

// PrepareRecord mocks base method
func (m *MockRecord) PrepareRecord() (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareRecord")
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareRecord indicates an expected call of PrepareRecord
func (mr *MockRecordMockRecorder) PrepareRecord() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareRecord", reflect.TypeOf((*MockRecord)(nil).PrepareRecord))
}
