// Copyright 2020 VMware, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/go-ipfix/pkg/entities (interfaces: Set)

// Package testing is a generated GoMock package.
package testing

import (
	bytes "bytes"
	gomock "github.com/golang/mock/gomock"
	entities "github.com/vmware/go-ipfix/pkg/entities"
	reflect "reflect"
)

// MockSet is a mock of Set interface
type MockSet struct {
	ctrl     *gomock.Controller
	recorder *MockSetMockRecorder
}

// MockSetMockRecorder is the mock recorder for MockSet
type MockSetMockRecorder struct {
	mock *MockSet
}

// NewMockSet creates a new mock instance
func NewMockSet(ctrl *gomock.Controller) *MockSet {
	mock := &MockSet{ctrl: ctrl}
	mock.recorder = &MockSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSet) EXPECT() *MockSetMockRecorder {
	return m.recorder
}

// AddRecord mocks base method
func (m *MockSet) AddRecord(arg0 []*entities.InfoElementWithValue, arg1 uint16, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRecord indicates an expected call of AddRecord
func (mr *MockSetMockRecorder) AddRecord(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockSet)(nil).AddRecord), arg0, arg1, arg2)
}

// FinishSet mocks base method
func (m *MockSet) FinishSet() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FinishSet")
}

// FinishSet indicates an expected call of FinishSet
func (mr *MockSetMockRecorder) FinishSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishSet", reflect.TypeOf((*MockSet)(nil).FinishSet))
}

// GetBuffLen mocks base method
func (m *MockSet) GetBuffLen() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuffLen")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetBuffLen indicates an expected call of GetBuffLen
func (mr *MockSetMockRecorder) GetBuffLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuffLen", reflect.TypeOf((*MockSet)(nil).GetBuffLen))
}

// GetBuffer mocks base method
func (m *MockSet) GetBuffer() *bytes.Buffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuffer")
	ret0, _ := ret[0].(*bytes.Buffer)
	return ret0
}

// GetBuffer indicates an expected call of GetBuffer
func (mr *MockSetMockRecorder) GetBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuffer", reflect.TypeOf((*MockSet)(nil).GetBuffer))
}

// GetNumberOfRecords mocks base method
func (m *MockSet) GetNumberOfRecords() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumberOfRecords")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetNumberOfRecords indicates an expected call of GetNumberOfRecords
func (mr *MockSetMockRecorder) GetNumberOfRecords() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumberOfRecords", reflect.TypeOf((*MockSet)(nil).GetNumberOfRecords))
}

// GetRecords mocks base method
func (m *MockSet) GetRecords() []entities.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecords")
	ret0, _ := ret[0].([]entities.Record)
	return ret0
}

// GetRecords indicates an expected call of GetRecords
func (mr *MockSetMockRecorder) GetRecords() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecords", reflect.TypeOf((*MockSet)(nil).GetRecords))
}

// GetSetType mocks base method
func (m *MockSet) GetSetType() entities.ContentType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetType")
	ret0, _ := ret[0].(entities.ContentType)
	return ret0
}

// GetSetType indicates an expected call of GetSetType
func (mr *MockSetMockRecorder) GetSetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetType", reflect.TypeOf((*MockSet)(nil).GetSetType))
}
