// Copyright 2021 VMware, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/go-ipfix/pkg/entities (interfaces: Record)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../license_templates/license_header.raw.txt -destination=testing/mock_record.go -package=testing github.com/vmware/go-ipfix/pkg/entities Record
//
// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	entities "github.com/vmware/go-ipfix/pkg/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRecord is a mock of Record interface.
type MockRecord struct {
	ctrl     *gomock.Controller
	recorder *MockRecordMockRecorder
}

// MockRecordMockRecorder is the mock recorder for MockRecord.
type MockRecordMockRecorder struct {
	mock *MockRecord
}

// NewMockRecord creates a new mock instance.
func NewMockRecord(ctrl *gomock.Controller) *MockRecord {
	mock := &MockRecord{ctrl: ctrl}
	mock.recorder = &MockRecordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecord) EXPECT() *MockRecordMockRecorder {
	return m.recorder
}

// AddInfoElement mocks base method.
func (m *MockRecord) AddInfoElement(arg0 entities.InfoElementWithValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInfoElement", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddInfoElement indicates an expected call of AddInfoElement.
func (mr *MockRecordMockRecorder) AddInfoElement(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInfoElement", reflect.TypeOf((*MockRecord)(nil).AddInfoElement), arg0)
}

// AppendToBuffer mocks base method.
func (m *MockRecord) AppendToBuffer(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendToBuffer", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendToBuffer indicates an expected call of AppendToBuffer.
func (mr *MockRecordMockRecorder) AppendToBuffer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendToBuffer", reflect.TypeOf((*MockRecord)(nil).AppendToBuffer), arg0)
}

// GetBuffer mocks base method.
func (m *MockRecord) GetBuffer() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuffer")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuffer indicates an expected call of GetBuffer.
func (mr *MockRecordMockRecorder) GetBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuffer", reflect.TypeOf((*MockRecord)(nil).GetBuffer))
}

// GetElementMap mocks base method.
func (m *MockRecord) GetElementMap() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetElementMap")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetElementMap indicates an expected call of GetElementMap.
func (mr *MockRecordMockRecorder) GetElementMap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetElementMap", reflect.TypeOf((*MockRecord)(nil).GetElementMap))
}

// GetFieldCount mocks base method.
func (m *MockRecord) GetFieldCount() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFieldCount")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetFieldCount indicates an expected call of GetFieldCount.
func (mr *MockRecordMockRecorder) GetFieldCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldCount", reflect.TypeOf((*MockRecord)(nil).GetFieldCount))
}

// GetInfoElementWithValue mocks base method.
func (m *MockRecord) GetInfoElementWithValue(arg0 string) (entities.InfoElementWithValue, int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfoElementWithValue", arg0)
	ret0, _ := ret[0].(entities.InfoElementWithValue)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetInfoElementWithValue indicates an expected call of GetInfoElementWithValue.
func (mr *MockRecordMockRecorder) GetInfoElementWithValue(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfoElementWithValue", reflect.TypeOf((*MockRecord)(nil).GetInfoElementWithValue), arg0)
}

// GetMinDataRecordLen mocks base method.
func (m *MockRecord) GetMinDataRecordLen() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinDataRecordLen")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetMinDataRecordLen indicates an expected call of GetMinDataRecordLen.
func (mr *MockRecordMockRecorder) GetMinDataRecordLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinDataRecordLen", reflect.TypeOf((*MockRecord)(nil).GetMinDataRecordLen))
}

// GetOrderedElementList mocks base method.
func (m *MockRecord) GetOrderedElementList() []entities.InfoElementWithValue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderedElementList")
	ret0, _ := ret[0].([]entities.InfoElementWithValue)
	return ret0
}

// GetOrderedElementList indicates an expected call of GetOrderedElementList.
func (mr *MockRecordMockRecorder) GetOrderedElementList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderedElementList", reflect.TypeOf((*MockRecord)(nil).GetOrderedElementList))
}

// GetRecordLength mocks base method.
func (m *MockRecord) GetRecordLength() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordLength")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRecordLength indicates an expected call of GetRecordLength.
func (mr *MockRecordMockRecorder) GetRecordLength() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordLength", reflect.TypeOf((*MockRecord)(nil).GetRecordLength))
}

// GetRecordType mocks base method.
func (m *MockRecord) GetRecordType() entities.ContentType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordType")
	ret0, _ := ret[0].(entities.ContentType)
	return ret0
}

// GetRecordType indicates an expected call of GetRecordType.
func (mr *MockRecordMockRecorder) GetRecordType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordType", reflect.TypeOf((*MockRecord)(nil).GetRecordType))
}

// GetTemplateID mocks base method.
func (m *MockRecord) GetTemplateID() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateID")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetTemplateID indicates an expected call of GetTemplateID.
func (mr *MockRecordMockRecorder) GetTemplateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateID", reflect.TypeOf((*MockRecord)(nil).GetTemplateID))
}

// PrepareRecord mocks base method.
func (m *MockRecord) PrepareRecord() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareRecord")
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareRecord indicates an expected call of PrepareRecord.
func (mr *MockRecordMockRecorder) PrepareRecord() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareRecord", reflect.TypeOf((*MockRecord)(nil).PrepareRecord))
}
