name: Build and push a release image

on:
  push:
    tags:
      - v*

jobs:
  build-ipfix-collector:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build go-ipfix Docker images and push to Antrea Docker registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG: ${{ github.ref }}
        run: |
          make docker-collector
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag antrea/ipfix-collector antrea/ipfix-collector:"${TAG:10}"
          docker push antrea/ipfix-collector:"${TAG:10}"
  build-kafka-collector:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build kafka-consumer Docker images and push to Antrea Docker registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG: ${{ github.ref }}
        run: |
          make docker-consumer
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag antrea/kafka-consumer antrea/kafka-consumer:"${TAG:10}"
          docker push antrea/kafka-consumer:"${TAG:10}"
