name: Upload assets to release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Build assets
        uses: actions/checkout@v2
        env:
          TAG: ${{ github.ref }}
        run: |
          mkdir assets
          VERSION="${TAG:10}" ./hack/release/prepare-assets.sh ./assets
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Upload ipfix-collector.yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./assets/ipfix-collector.yaml
          asset_name: ipfix-collector.yaml
          asset_content_type: application/octet-stream
