name: Upload assets to release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build collector binary for Linux amd64
        run: |
          make collector
      - name: Upload collector binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/collector
          asset_name: ipfix-collector-linux-x86_64
          asset_content_type: application/octet-stream
